Repository e-harp-intern/R4FY, pull requests merged in 2022-09, with the labels that each got.

#51 #16 アカウント作成画面機能実装・リファクタリング
  web/src/i18n/languages/ja.js
  web/src/views/CreateAccount.vue
Labels: Front, リファクタリング

#53 #19 ツアー予定作成機能実装しました
  web/src/views/CreateTour.vue
Labels: Front

#61 #20 ツアー取り消しボタンを追加
  api/db/seeds.rb
  web/.eslintrc.json
  web/src/assets/css/style.css
  web/src/i18n/languages/ja.js
  web/src/mixins/common.js
  web/src/mixins/table.js
  web/src/views/TourView.vue
Labels: 新機能・機能強化, Front

#144 #136 ツアー状態によって色を変更
  web/src/assets/css/color.css
  web/src/views/TourView.vue
Labels: Front

#146 #107 アカウント一覧を取得API作成
  api/app/controllers/api/v1/accounts_controller.rb
  api/config/routes.rb
Labels: API

#150 #108 アカウントの取得及び、表示、ソートまで実装
  web/src/components/SideMenu.vue
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/AccountView.vue
Labels: Front

#164 #69 ツアー担当者リセットボタン及び、機能追加
  web/src/i18n/languages/ja.js
  web/src/views/TourView.vue
Labels: Front

#171 #109 アカウント一覧を取得に検索を追加[名前・メールアドレス]
  api/app/controllers/api/v1/accounts_controller.rb
Labels: API

#173 アカウント検索機能追加
  web/src/views/AccountView.vue
Labels: Front

#139 #71 予定入力画面及び機能作成
  api/test/mailers/previews/guide_schedule_input_mailer_preview.rb
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/guide/InputSchedule.vue
Labels: Front

#176 #65 ツアー担当ガイド決定画面及び機能
  web/.eslintrc.json
  web/src/assets/css/color.css
  web/src/assets/css/style.css
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/SelectGuide.vue
  web/src/views/TourView.vue
Labels: 難易度：難, Front

#356 #264 マイアカウント情報画面作成
  web/src/components/SideMenu.vue
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/accounts/MyAccountView.vue
Labels: Front

#363 #187 アラートの文章をja.jsに移動
  web/src/i18n/languages/ja.js
  web/src/views/tours/TourDetailView.vue
Labels: Front, リファクタリング

#364 #219 文字定義を移動
  web/src/i18n/languages/ja.js
  web/src/views/tours/SelectGuidesView.vue
Labels: Front, リファクタリング

#367 #357 ツアー状態の色を変更
  web/src/assets/css/color.css
  web/src/views/ToursListView.vue
  web/src/views/tours/TourDetailView.vue
Labels: Front

#362 #106 ツアー一覧検索機能追加[デザインは未実装]
  web/src/i18n/languages/ja.js
  web/src/views/ToursListView.vue
Labels: Front

#399 削除ボタンと機能を実装
  web/src/i18n/languages/ja.js
  web/src/views/accounts/GuideDetailView.vue
Labels: Front

#401 パスワード変更画面及び機能作成
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/accounts/ChangePasswordView.vue
  web/src/views/accounts/MyAccountView.vue
Labels: Front

#403 #267 マイアカウント情報変更画面及び機能追加
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/accounts/ChangeMyaccountInfoView.vue
  web/src/views/accounts/MyAccountView.vue
Labels: Front

#404 #193 開始日時が過去だとalertを出すように変更
  web/src/i18n/languages/ja.js
  web/src/views/tours/CreateTourView.vue
Labels: Front

#406 #405 css一部変更
  web/src/views/accounts/MyAccountView.vue
Labels: バグ, Front

#411 #407 ツアー作成開始時間が過去かどうか確認を実装
  web/src/views/tours/CreateTourView.vue
Labels: バグ, Front

#414 #121 ガイド情報変更機能追加
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/accounts/ChangeGuideInfoView.vue
  web/src/views/accounts/GuideDetailView.vue
Labels: Front

#415 #412 キャンセルボタン追加
  web/src/views/accounts/ChangeMyaccountInfoView.vue
Labels: Front

#416 #413 キャンセルボタン機能追加
  web/src/views/accounts/ChangePasswordView.vue
Labels: Front

#417 #374 ツアー詳細変更画面まで作成[開始・終了・メモ未実施]
  web/src/i18n/languages/ja.js
  web/src/router/index.js
  web/src/views/tours/EditTourView.vue
  web/src/views/tours/TourDetailView.vue
Labels: Front

#450 #438 担当ガイド決定画面でマウスオーバーでメモ表示
  web/src/assets/css/table.scss
  web/src/i18n/languages/ja.js
  web/src/views/tours/SelectGuidesView.vue
Labels: Front
